name: grepp-app

services:

  grepp-web:
    container_name: grepp-web
    image: grepp-web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net-2

  grepp-db:
    image: mysql
    container_name: grepp-db
#    ports:
#      - "3308:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=grepp_app_1
      - MYSQL_PASSWORD=grepp_app_1!
      - MYSQL_DATABASE=grepp_exp_db
    networks:
      - net_2

  grepp-app:
    image: grepp-app:0.3
    container_name: grepp-app
#    ports:
#      - "8080:8080"
    networks:
      - net_2
    depends_on:
      - grepp-db

networks:
  net_2:
    name: net_2
    driver: bridge